mission:
  mode: ssh
  machine: embedded@localhost
  cmd: ros2 launch anime_bt run_mission.launch.xml robot:=true model_name:=inail2arm gui:=false mission_name:=scenario0 stage:=CAPPING use_gripper:=false disable_collision:=true
